### ISSUE TITLE
beta2blocks

### ISSUE THREAD

**Issue by gibberwocky** [nloyfer/wgbs_tools#49]
Hi

It's been a wee while since I played with this. I'm just looking at it again now, and I'm getting an error when attempting to run the beta_to_table tool:

`./wgbs_tools/src/python/beta_to_blocks.py:39: FutureWarning: is_monotonic is deprecated and will be removed in a future version. Use is_monotonic_increasing instead.
  if not pd.Index(df['startCpG']).is_monotonic:
./wgbs_tools/src/python/beta_to_blocks.py:42: FutureWarning: is_monotonic is deprecated and will be removed in a future version. Use is_monotonic_increasing instead.
  if not pd.Index(df['endCpG']).is_monotonic:
Traceback (most recent call last):
  File "./wgbs_tools/wgbstools", line 96, in <module>
    main()
  File "./wgbs_tools/wgbstools", line 63, in main
    importlib.import_module(args.command).main()
  File "./wgbs_tools/src/python/beta_to_table.py", line 154, in main
    for chunk in chunks:
  File "./wgbs_tools/src/python/beta_to_table.py", line 137, in beta2table_generator
    yield get_table(subset_blocks, gf, min_cov, threads, verbose)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./wgbs_tools/src/python/beta_to_table.py", line 99, in get_table
    with np.warnings.catch_warnings():
         ^^^^^^^^^^^
  File "./myconda/envs/meth/lib/python3.11/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'warnings'. Did you mean: 'hanning'?`

Here's my pip list:

numpy  1.24.1
pandas          1.5.3
pip             22.3
python-dateutil 2.8.2
pytz            2022.7.1
scipy           1.10.0
setuptools      65.5.0
six             1.16.0
wheel           0.37.1

Any thoughts?

Cheers

D

**Comment by gibberwocky** [comment]
Updated htslib, cloned the latest wgbs_tools, rebuilt genome, runs without error now.
